### PR TITLE
In the GitHub runner, merge artifacts after all platforms have built.

### LINKED ISSUE #20: Package the artifacts of the various platform builds into a single archive
Package the artifacts of the various platform builds into a single archive ready to be used or uploaded as a release.

Todo from https://github.com/maiself/godot-python-extension/issues/14

### PR DESCRIPTION
**Pull request by Ivorforce**
Closes #20.

### CODE REVIEW

**Comment by fire** [comment]
Needs a rebase

**Comment by maiself** [comment]
Merge job is falling

**Comment by fire** [comment]
image

Do not match `godot-python-*`

**Comment by Ivorforce** [comment]
Merge was failing because upload-artifact@v3 is not compatible with merge@v4, see: https://github.com/actions/upload-artifact/tree/main/merge

**Review by fire — APPROVED** [review]

**Pull request merged**
